export const CART_ACTION_TYPES = {
    TOGGLE_CART: "TOGGLE_CART",
    SET_CART_ITEMS: "SET_CART_ITEMS",
    ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
    REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
    CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
};
